# add user specific settings
---

# Fetch home directories of users https://stackoverflow.com/a/48892377
- user:
    name: '{{ user }}'
    state: present
  register: user_info
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: Transform user_homes into a dictionary
  set_fact:
    user_info_dict: "{{ user_info_dict | default({}) | combine({item['user']: item}) }}"
  with_items: "{{ user_info.results }}"

- name: add user to group [always report as changed]
  become: yes
  changed_when: true
  command: "usermod -a -G microk8s {{ user }}"
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  register: usermod_output

- name: Create .kube folder for the user
  become: yes
  become_user: '{{ user }}'
  file:
    path: "{{ user_info_dict[user]['home'] }}/.kube"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    mode: 0750
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

# fix (slechta): [https://github.com/accanto-systems/ansible-role-microk8s/issues/2],
- name: create kubectl config [always report as changed]
  become: yes
  changed_when: true
  shell: source /etc/profile.d/apps-bin-path.sh && microk8s config > {{ user_info_dict[user]['home'] }}/.kube/config
  args:
    executable: /bin/bash
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: reaffirm permission on files
  become: yes
  file:
    path: "{{ user_info_dict[user]['home'] }}/.kube"
    state: directory
    owner: '{{ user }}'
    group: '{{ user }}'
    recurse: yes
    mode: 0750
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

# fix (slechta): [https://github.com/accanto-systems/ansible-role-microk8s/issues/2]
- name: add helm repository to user [always report as changed]
  become: yes
  become_user: '{{ item.0 }}'
  shell: "source /etc/profile.d/apps-bin-path.sh && helm repo add {{ item.1.name }} {{ item.1.url }}"
  args:
    executable: /bin/bash
  changed_when: true
  with_nested:
    - "{{ users }}"
    - "{{ helm3_repositories }}"
  when: microk8s_plugins.helm3

# fix (slechta): [https://github.com/accanto-systems/ansible-role-microk8s/issues/2]
- name: update helm repos [always report as changed]
  become: yes
  become_user: '{{ user }}'
  shell: "source /etc/profile.d/apps-bin-path.sh && helm repo update"
  args:
    executable: /bin/bash
  changed_when: true
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'
  when: microk8s_plugins.helm3
